### ISSUE TITLE
Should allow Python 3.9 as this is the default now on Arch

### ISSUE THREAD

**Issue by kootenpv** [rcaloras/bashhub-client#100]

**Comment by rcaloras** [comment]
Is there no older version installed on Arch? +1 on supporting the latest, but curious if this is causing the install to fail entirely.

**Comment by kootenpv** [comment]
I just manually bumped the check for <3.9 to 3.10 and it installed & works just fine 👌

**Comment by rcaloras** [comment]
Fixed in 2.2.0. https://github.com/rcaloras/bashhub-client/commit/ebe48906943636ffcfbfb865826f043ffe1deaa4
