### ISSUE TITLE
search a specific char inside a command

### ISSUE THREAD

**Issue by francoataffarel** [rcaloras/bashhub-client#112]
Hello,

i realized that is not possible search a specific char inside a command. Example:

a comand: subfinder -d asdas.com

ctrl +b search for 'sub'

show nothing

can u make this possible?

thanks for everything

**Comment by rcaloras** [comment]
@francoataffarel thanks for the feedback! This unfortunately is not possible with how Bashhub.com's search currently works as it does not support partial words or regexes. I believe it does allow for words/commands delineated by hyphens though. 

Alternatively, if you'd like to run your own version of Bashhub server, there is another open source project which supports regex search https://github.com/nicksherron/bashhub-server#using-regex. This is not an official version of Bashhub's server, but is used by several people in the community.
