### ISSUE TITLE
Getting all stored commands from all systems at once

### ISSUE THREAD

**Issue by hoefkensj** [rcaloras/bashhub-client#118]
```bash
hoefkens@ms7976 /opt/local $ bashhub status
=== Bashhub Status
https://bashhub.com/hoefkensj
Total Commands: 41597
Total Sessions: 3024
Total Systems:  6
===
Session PID 894415 Started 2 days ago
Commands In Session: 24
Commands Today: 24

hoefkens@ms7976 /opt/local $ bh -n 41597 |wc -l
10000
hoefkens@ms7976 /opt/local $
```
ive been trying to get all  stored commands in bashub  so i can locally store them in a history file. and  my bindkeys for backward history search can search in all commands (and some other stuff , like having a bad connection, having a offline copy would bee nice)
ive tried multiple approaches to get them all but
using the -sys flag , allows me to get only commands of the current system, wich would be okay if there was a way to also only get the commands of another system, and get the whole history in chuncks that way. Problem, 4 of the 6 systems listed are previous installs of my machines so the actual system that would be able to get the commands with -sys does not exist anymore
and , naming a new system identical to a existing system is not allowed by the installer.

-ses : would also be fine if there was a way to get a list of all session idea's  but having to guess all possible 3024 of PID numbers that are currently stored is a nonestarter , (even if i could possibly get them 'brute-force'
`seq 99999999| xargs -n 1 bh -dups -n 41597 -sys -ses >>~/bh_history`
wich would be the nice way by doing it serial but cmon

 smth like a one time full sync should be possible not? or expand the -n limit to -1 for no limit (instead of the ceiling of 10k, ) 
or maybe allowing for a full download but gzipped 
or even allow -n to specify a starting and ending point so `bh -n 10000-20000`  would start at 20k commands ago and get them til 10k commands ago.

perhaps its also not a bad idea to allow for installation in a custom location and less dependant on files being in ~/.bashhub  cluttering the home dir some more , but leaving just a bashbub.config  in ~/.config/ and defaulting to install to /opt (or ad a --user flag to the setup command to install to the users .local/share folder or whater. 

srry if this was the wrong place to post this but could not find a better suited spot .

**Comment by rcaloras** [comment]
Hi @hoefkensj, thanks for the feedback. We can export your history for you if you'd like. Just shoot an email requesting it to support@bashhub.com

**Comment by hoefkensj** [comment]
that would be nice but not really a permanent solution i feel . 
was looking trough the code and figured it should be pretty easy to change (in bh.py) : 
```
@click.option("-sys",
"--system",
help="Search for commands created on this system.",
default=False,
)
```
and then correspondingly:
```
system_name = system or  BH_SYSTEM_NAME if system else None
``` or smth. wifh would allow you to simply get the history saved on a prticular machine different. if you know the name of tthat system... wich got me to the next issue: i can see i have 6 systems that i have registered , but no way oi finding their names... still no perfect solution either since any system with more then ~10k would stilll be incomplete , and since the ~10k limit is enforced by the server (what i don't really understand, i get that some people have massive command counts , but still its plain text , and since you upload every command executed its not that the server would experience an overload , given that how many times people will want to get their entire history back?)
