### ISSUE TITLE
Latest Python (3.11) not support

### ISSUE THREAD

**Issue by tanducmai** [rcaloras/bashhub-client#124]
When setting up bashhub using the following command:

```bash
curl -OL https://bashhub.com/setup && $SHELL setup
```

The following message appears:

```text
 Sorry can't seem to find a version of python 3.5-3.10 or 2.7.9+ installed
```

This is due to my machine running Python latest version - 3.11

**Comment by rcaloras** [comment]
Just published 2.4.0 which should support it. Feel free to run `curl -OL https://bashhub.com/setup && $SHELL setup` again.
