### ISSUE TITLE
`bh -i foo` causes crash on mac

### ISSUE THREAD

**Issue by umjammer** [rcaloras/bashhub-client#129]
searching by cui cause crash.
other commands w/o cui work fine.

could you find any ideas from the crash log?

### crash log

https://gist.github.com/umjammer/748eef9fee247a0e06cdd8a3c552497f

### command

```shell
 $ bh -i anyword
```

### env

* bh
```shell
$ bh --version
Bashhub 2.4.1 (python 3.9.6)
```
* macos ventura m2
```shell
$ uname -mrs
Darwin 22.6.0 arm64
$ sw_vers
ProductName:            macOS
ProductVersion:         13.5.2
BuildVersion:           22G91
```
* shell
```shell
$ $SHELL --version
zsh 5.9 (x86_64-apple-darwin22.0)
```

* python
```shell
$ cat ~/.bashhub/env/pyvenv.cfg
home = /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9
implementation = CPython
version_info = 3.9.6.final.0
virtualenv = 20.10.0
include-system-site-packages = false
base-prefix = /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9
base-exec-prefix = /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9
base-executable = /Applications/Xcode.app/Contents/Developer/usr/bin/python3
```

**Comment by umjammer** [comment]
i upgraded masOS to Sonoma, then this issue is not reproduced.

env:
 * macOS 14.1.1
 * Python 3.9.6 (default, Oct  1 2023, 17:38:10) [Clang 15.0.0 (clang-1500.0.40.1)]

i'm ok to close this issue, but how about Ventura users?

**Comment by rcaloras** [comment]
hey @umjammer thanks for opening. Glad to hear it's working now. Not sure why this was happening specifically for Ventura, but can associate it if more come in.
