### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by darkstar** [rcaloras/bashhub-client#13]
Currently, the setup script does not work behind a proxy. Error message is as follows
```
Setup Error:
No JSON object could be decoded
Traceback (most recent call last):
  File "/root/.bashhub/env/lib/python2.7/site-packages/bashhub/bashhub_setup.py", line 166, in main
    user_id = rest_client.register_user(register_user)
  File "/root/.bashhub/env/lib/python2.7/site-packages/bashhub/rest_client.py", line 37, in register_user
    return response.json()
  File "/root/.bashhub/env/lib/python2.7/site-packages/requests/models.py", line 651, in json
    return json.loads(self.text or self.content, **kwargs)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Please run 'bashhub setup' after restarting your terminal session.
```
Environment variables are set correctly and proxy works (curl, pip, etc. all work fine for example):
```
[root@centos7 ~]# printenv | grep proxy
http_proxy=http://10.84.4.24:3128
ftp_proxy=http://10.84.4.24:3128
https_proxy=http://10.84.4.24:3128
[root@centos7 ~]# curl -Ls https://bashhub.com/setup | head -3
#!/bin/bash -e
#
# Bashhub.com Installation shell script
```

**Comment by rcaloras** [comment]
@darkstar Thanks for filing the issue and checking out Bashhub! 

Looks like this might be an issue with python requests. http://docs.python-requests.org/en/latest/user/advanced/#proxies Can you try to export your proxy env vars in caps like in the requests examples? e.g.
```bash
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

**Comment by darkstar** [comment]
Hm. Digging a bit deeper into this it looks like it's a problem on our end. For some reason, the page I'm getting via Python is not the same as the one I'm getting from my browser. Seems our upstream proxy somehow blocks the https://bashhub.com URL for me here. Which is strange because I can look at the page in a browser through the same proxy just fine.

I'll close this for now and see if I can get that sorted out first.

Thanks
