### ISSUE TITLE
support recent python versions

### ISSUE THREAD

**Issue by casperdcl** [rcaloras/bashhub-client#136]
I managed to get `pip install ./bashhub-client` working (on conda `python=3.12`) by making the following changes:

- unpin dependency versions in `setup.py`
- fix super old/unmaintained [PyCLI](https://pythonhosted.org/pyCLI) dependency (https://github.com/whilp/cli) - similar to https://github.com/eaitelecom/cli/commit/7e6464114826247fa3190e72833f788eeecd4936
  + replace `except Exception, e` with `except Exception as e` in `cli/app.py`
  + replace `except SystemExit, e` with `except SystemExit as e` in `cli/app.py`
  + define `basestring = (str, bytes)` at the top of `cli/_ext/argparse.py`

probably should drop pyCLI dependency.

**Comment by rcaloras** [comment]
@casperdcl what version were you installing? Latest is `2.4.1`. pyCLI dependency was dropped a couple years ago in `2.30`. Can you try installing for 2.4.1. We can upgrade the install script if it's supported.

**Comment by casperdcl** [comment]
oops sorry was accidentally pulling from my fork rather than upstream.

**Comment by rcaloras** [comment]
All good. Sounds like 3.12 is working though. Good to know.

**Comment by ivomarino** [comment]
still fails on latest fedora, works when installing `python3.11` via `dnf`. Default version is:

```
python3 --version
Python 3.12.2
```
