### ISSUE TITLE
Publish server implementation

### ISSUE THREAD

**Issue by prauscher** [rcaloras/bashhub-client#16]
Obvious imho. Sorry, but probably most shellusers should not trust a external service, especially as there is no encryption whatsoever.

**Comment by rcaloras** [comment]
@prauscher thanks for checking out Bashhub. That's part of the plan, to eventually open source the server so if users would like they can run scaled down private instances.

Trust is difficult, and the idea of sending your bash history to a central cloud is definitely not for everyone. Here's some of the current practices regarding [Security and Privacy](https://github.com/rcaloras/bashhub-client/wiki/Security-and-Privacy). Bashhub currently supports storage level encryption, but what would be best is application level. This is very difficult to do while still maintaining high quality Text Search on the server. I'm currently researching a few ways to pull it off. In the meantime all users are encouraged to filter their commands. 

Some users @andrew-morris have hacked together some basic but slick client side solutions for encryption if you're interested.

**Comment by rcaloras** [comment]
@prauscher Closing this as it'll hopefully happen somewhere down the road. I'd like the make the api public first.

**Comment by pixie79** [comment]
Hi,

I would like to second this request - it would be very useful for audit of private systems, especially if we can optionally turn off the delete option as it would allow a method to audit users better.

Regards

Mark
