### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by pahko** [rcaloras/bashhub-client#20]
Since today I'm getting this error when I try to search for something:

```bash
$ bh "regis"
Oops, look like an exception occured: No JSON object could be decoded
```

Regards

**Comment by rcaloras** [comment]
Hey @pahko! Sorry for exception. I'm in the process of making a breaking change to the API and unfortunately it means downtime for search. I should have a fix shortly that'll require an update. Would love for you to give it a try when it's set. 

Thanks for opening an issue :+1:

**Comment by rcaloras** [comment]
@chromedome FYI

**Comment by pahko** [comment]
thanks for the super fast response @rcaloras !!

that's great!

looking forward to hear the fix is in prod :).

**Comment by cromedome** [comment]
@rcaloras Thanks! I will let you know how it works out for me!

**Comment by tomaadland** [comment]
I'm having the same problem, looking forward for the fix :)

**Comment by bilalbaqar** [comment]
Has the fix been pushed? Still facing this error!

**Comment by rcaloras** [comment]
Hey @bilalbaqar, sorry not yet. Hoping to have something by end of week if not sooner. Thanks for your patience.

**Comment by bilalbaqar** [comment]
Thanks. Eager to try it out.

**Comment by andrew-morris** [comment]
@rcaloras +1 

I'm also seeing this issue. Do you have a time frame in mind?

Thanks for all your work!

**Comment by rcaloras** [comment]
Hey @andrew-morris! Sorry for the downtime, direct messaged you. Thanks for the continued support.

**Comment by kootenpv** [comment]
Also facing the issue, I'll remove the issue I created.

**Comment by rcaloras** [comment]
Hey @kootenpv! Direct messaged you. Please follow up over there if needed :+1:

**Comment by cromedome** [comment]
@rcaloras Any progress here?

**Comment by rcaloras** [comment]
Hey @cromedome, shot you a direct message. Follow up with me there if you'd like.

**Comment by bilalbaqar** [comment]
Also waiting for the fix.

**Comment by sudeeptarlekar-webonise** [comment]
Getting error as well, waiting for fix.

**Comment by bilalbaqar** [comment]
Seams like its fixed in the 1.0.0 dev branch 

git clone https://github.com/rcaloras/bashhub-client.git
cd bashhub-client/
git checkout 1.0.0-dev
git reset --hard origin/1.0.0-dev
sudo python setup.py install
sudo apt-get install python-pip
sudo pip install humanize==0.5.1
sudo pip install inflection==0.2.1
sudo pip install pymongo==2.6
sudo pip install pyCLI==2.0.3
sudo pip install python-dateutil==2.4
sudo pip install npyscreen==4.9.1
sudo pip install click==3.3
sudo pip install jsonpickle==0.7.0
sudo pip install requests==1.2.3
bashhub setup

**Comment by rcaloras** [comment]
@sudeeptarlekar-webonise @bilalbaqar Hey guys, yes it's being addressed in that dev branch. Hoping to have it merged in the next week. It's stable, but I'm having a few users review it before moving it to master. There may still be a breaking change before then. 

A better way to install it is do the default install, then `bashhub update 1.0.0-dev` this will setup bashhub's home directory and isolated virtual environment properly.

**Comment by rcaloras** [comment]
I'll send out an email to all users when 1.0.0 is released to run `bashhub update`. Thanks for your continued support and patience.

**Comment by rcaloras** [comment]
This is now fixed and released in [1.0.0](https://github.com/rcaloras/bashhub-client/releases/tag/1.0.0) :) Please run `bashhub update` to get the latest version.

Also if you have one, please discard any private instance urls (i.e. `export BH_URL="..."`), they won't work with the latest client.

Thanks for the continued support and patience. Please feel free to open an issue with any feedback, ideas, or trouble you're having.

**Comment by kootenpv** [comment]
Great job Ryan! Awesome that you were able to allow the users to fix the issue with just simply `basshub update`. The fast few weeks I've thought multiple times that it would have been great to be able to use the tool: thanks!

**Comment by tomaadland** [comment]
Works like a charm :+1: awesome job @rcaloras

**Comment by cromedome** [comment]
Great job! thanks @rcaloras!
