### ISSUE TITLE
Install inside tmux session doesn't add bh or bashhub to $PATH.

### ISSUE THREAD

**Issue by jonatasbaldin** [rcaloras/bashhub-client#24]
Hey! I installed Bashhub inside a tmux session. Installation run just fine, but I got this error:

```
$ bh
Oops, look like an exception occured: No JSON object could be decoded
```

Also, outside the tmux session, the commands **bh** and **bashhub** aren't in my $PATH. I reinstalled the application but the situation remains still.
When running the command with full path `$USER/.bashhub/bin/bh`, the same error above is issued.

**Comment by rcaloras** [comment]
Hey @jonatasbaldin! Thanks for checking out Bashhub. The first issue has to do with some breaking changes in the api causing search to be down. That's being tracked as part of https://github.com/rcaloras/bashhub-client/issues/20

The second issue in regards to commands not being on your path looks legitimate. I'm going to rename the title of this Issue.

**Comment by jonatasbaldin** [comment]
Nice! Gonna follow #20, thanks!

**Comment by rcaloras** [comment]
@jonatasbaldin could you try a reinstall now that [1.0.0](https://github.com/rcaloras/bashhub-client/releases/tag/1.0.0) is out? 

If it's still an issue, I'm wondering why tmux would prevent it from adding it to your path.

**Comment by jonatasbaldin** [comment]
@rcaloras Hi! 

Now the **bh** command works, everything is being logged on a normal termina.
But inside tmux, the search works, but the commands aren't logged at Bashub.

If you need any information, let me know!

**Comment by rcaloras** [comment]
@jonatasbaldin Strange search would work, but it's not properly logging commands.

Works inside tmux for me, I wonder if there's something about your bash configuration.

Which bash config file has your bashhub installation? `.bash_profile`? Could you check a few things for me from inside tmux?
```bash
# Bashhub is on your path
which bashhub
# Contents of your prompt command
echo $PROMPT_COMMAND 
# Contents of preexec 
echo ${preexec_functions[@]}
```

Should see something like:
```bash
$ which bashhub
/Users/rcaloras/.bashhub/bin/bashhub
$ echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd; update_terminal_cwd; __bp_interactive_mode;
$ echo ${preexec_functions[@]}
preexec __bh_preexec
```

**Comment by jonatasbaldin** [comment]
Hey, sorry for the lateness, here's the output:

```bash
jonatas@jonatas-laptop:~/vagrant/ror$ which bashhub                                                                                   
/home/jonatas/.bashhub/bin/bashhub
jonatas@jonatas-laptop:~/vagrant/ror$ echo $PROMPT_COMMAND 
__bp_precmd_invoke_cmd; dbus-send --type=method_call --session --dest=net.launchpad.pantheon-terminal /net/launchpad/pantheon_terminal org.pan
theon.terminal.ProcessFinished string:$PANTHEON_TERMINAL_ID string:"$(history 1 | cut -c 8-)" >/dev/null 2>&1; __bp_interactive_mode;
jonatas@jonatas-laptop:~/vagrant/ror$ echo ${preexec_functions[@]}
__bh_preexec
jonatas@jonatas-laptop:~/vagrant/ror$ echo ${precmd_functions[@]}
__bh_precmd __bh_bash_precmd
``` 

The problem persists, outside tmux the commands are logged, inside, not.

**Comment by rcaloras** [comment]
@jonatasbaldin And which bash config file has your bashhub installation? .bash_profile?

Could you also check the trap and tmux version?

```bash
# Check our trap is set correctly
$ trap 
trap -- '__bp_preexec_invoke_exec' DEBUG
# Check the tmux version
$ tmux -V
tmux 2.1
```

I'm not sure why you don't have **preexec** or **preecmd** defined in your function arrays. Although you shouldn't need them, if bash-preexec was properly installed it should add them by default. Wondering if you have an old version installed or something that is blocking it.

**Comment by jonatasbaldin** [comment]
Hi.

.bash_profile loads .profie, which has this conf related to Bashhub.
```
### Bashhub.com Installation.
### This Should be at the EOF. https://bashhub.com/docs
if [ -f ~/.bashhub/bashhub.sh ]; then
    source ~/.bashhub/bashhub.sh
fi
```

Also, the other outputs:
```
jonatas@jonatas-laptop:~$ trap
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU

jonatas@jonatas-laptop:~$ tmux -V
tmux 2.0
```

Does it help?


2016-04-08 11:24 GMT-03:00 Ryan Caloras <notifications@github.com>:

> @jonatasbaldin <https://github.com/jonatasbaldin> And which bash config
> file has your bashhub installation? .bash_profile?
>
> Could you also check the trap and tmux version?
>
> # Check our trap is set correctly
> $ trap trap -- '__bp_preexec_invoke_exec' DEBUG# Check the tmux version
> $ tmux -V
> tmux 2.1
>
> I'm not sure why you don't have *preexec* or *preecmd* defined in your
> function arrays. Although you shouldn't need them, if bash-preexec was
> properly installed it should add them by default. Wondering if you have an
> old version installed or something that is blocking it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rcaloras/bashhub-client/issues/24#issuecomment-207451310>
>



-- 
____________________________
Jonatas Baldin
deployeveryday.com

**Comment by rcaloras** [comment]
@jonatasbaldin Looks like there's something causing the Debug trap to be removed or not added. This is done via the installation of [bash-preexec](https://github.com/rcaloras/bash-preexec). It's what invokes bashhub to save a command. 

```bash
# Trap should contain bash-preexec's hook
$ trap 
trap -- '__bp_preexec_invoke_exec' DEBUG
```

Could you try moving the installation hook to be the last line of your .bash_profile? Something else might be overwriting the DEBUG trap. 

Could you also try commenting out the bashhub profile hook and then sourcing bash-preexec.sh directly to see if your trap works right? e.g.
```bash
# First comment out source ~/.bashhub/bashhub.sh from your profile and start a new session.
# Check that bash-preexec is not imported
$ [ -z "$__bp_imported" ] && echo "undefined"
=> undefined
# Source bash-preexec directly
$ source ~/.bashhub/deps/bash-preexec.sh 
```
Then check the trap and see if you can create any of the examples in [bash-preexec's README.md](https://github.com/rcaloras/bash-preexec#usage). If you can figure out why bash-preexec is not working, bashhub should follow suit :+1:

**Comment by rcaloras** [comment]
@jonatasbaldin Is this still an issue? There's an upgrade of bash-preexec in the latest release that I believe could fix it if it's still a problem. `bashhub update` to get the latest.

**Comment by rcaloras** [comment]
@jonatasbaldin bump! Could you try to run `bashhub update` and see if this still an issue.

**Comment by rcaloras** [comment]
Don't believe this is an issue any longer and I cannot recreate @jonatasbaldin feel free to reopen if needed.
