### ISSUE TITLE
Using iTerm2 + shell integration won't save commands.

### ISSUE THREAD

**Issue by rcaloras** [rcaloras/bashhub-client#27]
@tmccartan https://bashhub.com/u/tmccartan Spotted this since there's a conflict with [bash-preexec](https://github.com/rcaloras/bash-preexec) and [iTerm2](https://github.com/gnachman/iterm2) with shell integration.

Looks like both libraries try to make a play for the debug trap. I'm wondering if we can standardize to use one library and just queue up preexec functions from there.

**Comment by rcaloras** [comment]
@tmccartan Believe this should be fixed in the latest dev version of Bashhub. Could you try updating to it and see if it's saving properly?

```bash
$ bashhub update 1.0.2-dev
```
Let me know if it works.

**Comment by tmccartan** [comment]
Works like a charm 

🍔 🍟

**Comment by rcaloras** [comment]
Great! Addressed in 1.0.2-dev. I'll merge soon.
