### ISSUE TITLE
Bashhub installation can break without notifying users.

### ISSUE THREAD

**Issue by rcaloras** [rcaloras/bashhub-client#28]
A handful of installs have broken due to changes in a users shell environment or changes in configuration (e.g. lack of auth token, or bad config file). This causes commands to not save properly without letting the user know at all. 

It'd be nice to do some basic checks on session start to verify that Bashhub is working. If not, we can output a helpful warning message to notify a user that their installation needs to be fixed.
#27 is one example that's popped up in the past few months.

**Comment by kootenpv** [comment]
Seconded.

**Comment by rcaloras** [comment]
@kootenpv Thanks!

Any idea what the issue you noticed? I have some commits addressing this as part of the 1.0.2-dev https://github.com/rcaloras/bashhub-client/commit/cb1470a2d32cc8c3b61a135409b31975a4b84363.

Mainly checks that your config and auth token look setup correctly and if you're using bash that your DEBUG trap is wired properly by bash-preexec.

**Comment by rcaloras** [comment]
All the checks happen at session start and are written in bash. 

I'm trying to find a good way to check client failures (e.g. a bad auth token) without making a blocking external call. I'd also like to avoid having to use python if possible to keep it fast at session start.

**Comment by kootenpv** [comment]
Actually, I did not see any problems yet: I just see it as a realistic problem :)

**Comment by rcaloras** [comment]
👍 Ahh right on :)

Yeah with this change it'll display any messaging on session start. So when you open a new tab or terminal if it detects a problem you'll get a message.

**Comment by rcaloras** [comment]
Have about [5 checks](https://github.com/rcaloras/bashhub-client/blob/master/bashhub/shell/deps/lib-bashhub.sh#L113) now as part of the latest version 1.1.0. 

I want to add one more that will check or know the validity of your token some how. I don't want to block to make the call though, thinking I might be able to set something if a save command fails perhaps then notify you next time the shell starts.

**Comment by rcaloras** [comment]
Closing based on original 5 checks added in 1.1.0.
