### ISSUE TITLE
Installation Fails on Mac with Anaconda

### ISSUE THREAD

**Issue by virpatel524** [rcaloras/bashhub-client#31]
Trying to install this program on a Mac and get the following issue: 

_**New python executable in env/bin/python2.7
Also creating executable in env/bin/python
Installing distribute.............
  Complete output from command /Users/blank/.bashhub/env/bin/python2.7 -c "#!python
\"\"\"Bootstra...   sys.exit(main())
":
  Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "/Users/blank/anaconda/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Users/blank/anaconda/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Users/blank/.bashhub/env/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Users/blank/.bashhub/env/lib/python2.7/lib-dynload/_io.so
  Expected in: dynamic lookup

----------------------------------------
...Installing distribute...done.
Traceback (most recent call last):
  File "virtualenv-1.9.1/virtualenv.py", line 2577, in <module>
    main()
  File "virtualenv-1.9.1/virtualenv.py", line 979, in main
    no_pip=options.no_pip)
  File "virtualenv-1.9.1/virtualenv.py", line 1088, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv-1.9.1/virtualenv.py", line 616, in install_distribute
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv-1.9.1/virtualenv.py", line 583, in _install_req
    cwd=cwd)
  File "virtualenv-1.9.1/virtualenv.py", line 1057, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/bank/.bashhub/env/bin/python2.7 -c "#!python
\"\"\"Bootstra...   sys.exit(main())
" failed with error code 1**_

What gives?

**Comment by rcaloras** [comment]
Hey @virpatel524! Believe this is an issue with anaconda. https://github.com/conda/conda/issues/1367

What version of python are you running?
```bash
$ python -V
```
If you're running 2.7.10 or higher looks like a simple work around from that thread is to downgrade to 2.7.9. Give it a shot and let me know if there's anything else I can help with.

**Comment by virpatel524** [comment]
Yup. Fixed it. Thanks so much!


On May 31, 2016 at 3:05:36 PM, Ryan Caloras (notifications@github.com)
wrote:

Hey @virpatel524 <https://github.com/virpatel524>! Believe this is an issue
with anaconda. conda/conda#1367 <https://github.com/conda/conda/issues/1367>

What version of python are you running?

$ python -V

If you're running 2.7.10 or higher looks like a simple work around from
that thread is to downgrade to 2.7.9. Give it a shot and let me know if
there's anything else I can help with.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rcaloras/bashhub-client/issues/31#issuecomment-222803822>,
or mute the thread
<https://github.com/notifications/unsubscribe/AGcEMnHlegxV9xgURzuxCyXKVi5dcNmdks5qHJSNgaJpZM4Iq2Br>
.

**Comment by rcaloras** [comment]
Great! Would love to hear your feedback on Bashhub. Enjoy! 👍

**Comment by tantrev** [comment]
As a daily anaconda user, it'd be really nice if there was another workaround besides downgrading python.

**Comment by casperdcl** [comment]
same issue with conda on ubuntu. Solved by deactivating the conda environment (dropping back to system python) before running `bash setup` or `bashhub update`.
