### ISSUE TITLE
How to disable bashhub's C-b kbd on zsh?

### ISSUE THREAD

**Issue by cmal** [rcaloras/bashhub-client#39]
How to disable bashhub's C-b kbd on zsh?
I installed bashhub just now, but the C-b kbd drives me crazy.
How to disable it?
And what other kbds does bashhub provide?
Thanks!

**Comment by rcaloras** [comment]
Hey @cmal,

One simply way you can disable it is via `~/.bashhub/bashhub.zsh`. Simply comment out:

```bash
bindkey -s '^b' "bh -i\n"
```

That's the only preconfigured key binding. You can always add more yourself via your .zshrc or .bashrc.

**Comment by cmal** [comment]
ok, thanks a lot!
