### ISSUE TITLE
consider supporting C-n (down) C-p (up) in interactive navigation

### ISSUE THREAD

**Issue by kpurdon** [rcaloras/bashhub-client#48]
While `j,k,n,p` work `C-n, C-p` do not. I think these should be able to be added according to http://npyscreen.readthedocs.io/keybindings.html which shows `^n` as the format for `Control-n`.

**Comment by rcaloras** [comment]
@kpurdon Thanks for opening and also posting on [reddit](https://www.reddit.com/r/coolgithubprojects/comments/6y43e7/bashhub_bash_history_in_the_cloud_indexed_and/)! Love the hype :+1: :pray: :+1: 

Any interest in submitting a PR?

**Comment by kpurdon** [comment]
I took a quick peek and wasn't able to get the change working right away, and just don't have the free time! It's working well enough for me as-is. More of a nice to have. Thanks.

**Comment by rcaloras** [comment]
Looks like this was partially addressed via https://github.com/rcaloras/bashhub-client/pull/43 Could probably just extend that.

**Comment by kpurdon** [comment]
Just using n & p work fine ... closing since I don't need this anymore and nobody is actively taking this on.
