### ISSUE TITLE
Create necessary bashfile if it doesn't exist.

### ISSUE THREAD

**Issue by Benuuu** [rcaloras/bashhub-client#5]
I'm running into "No bashfile (e.g. .profile, .bashrc, etc) could be found" on a new machine.

Could you have the setup script create the necessary files.

**Comment by rcaloras** [comment]
Seems simple enough. What do you think the flow should be like? Maybe something like:

```bash
=> No bashfile (e.g. .profile, .bashrc, etc) could be found.
Would you like to generate one (Y/N)?: yes
=> Generated new blank "$HOME/.bashrc"
```

**Comment by Benuuu** [comment]
:+1:

**Comment by rcaloras** [comment]
@Benuuu want to test on your new box?
