### ISSUE TITLE
Using timestamps

### ISSUE THREAD

**Issue by kootenpv** [rcaloras/bashhub-client#51]
Is there a way to get information about when a line was created?

Also, if I would add `echo 'export HISTTIMEFORMAT="%d/%m/%y %T "'` to bashrc, will this not break anything?

**Comment by rcaloras** [comment]
@kootenpv, do you mean like when a line of history was created? From interactive search you can access the command details by pressing 'space' or 'i'. https://github.com/rcaloras/bashhub-client#command-details

Did you mean output it with the command?

You should also be able to add that to your bashrc with it breaking.

**Comment by kootenpv** [comment]
Oh, I did not know that it is already there. But indeed, the question was mostly if it would break.
