### ISSUE TITLE
Import / export

### ISSUE THREAD

**Issue by Pawamoy** [rcaloras/bashhub-client#52]
Is there a way to import commands to bashup from bash history, and another way to export bashub contents to a local file?

**Comment by rcaloras** [comment]
Hey @Pawamoy, you can import commands as described in this older issue https://github.com/rcaloras/bashhub-client/issues/42

There's currently no way to export commands to a local file, but if you don't care about the additional meta data you can grab up to the last 10k commands via `bh -n 10000 > last-10k.log`

**Comment by Pawamoy** [comment]
I see, that will do, thank you 😄 !
