### ISSUE TITLE
Feature request: print to stdout command info like time of execution

### ISSUE THREAD

**Issue by infokiller** [rcaloras/bashhub-client#55]
Context: #38 

It would be great if the `bh` command could take flags that print the datetime that the command was executed on, and possibly other data. For example, using something like `bh --show-execution-datetime` could print the datetime in a separate column in the output.

**Comment by rcaloras** [comment]
Looks like this is actually already included in our API response:
https://github.com/rcaloras/bashhub-client/blob/master/bashhub/model/min_command.py#L11

This should be straight forward to extend bh.py to include a param to print the time stamp as part of:
https://github.com/rcaloras/bashhub-client/blob/master/bashhub/bh.py#L49

Right now all it fetches is the command, but it has both the time and uuid to print based on a flag. @infokiller or @simeg interested in submitting a PR?

**Comment by infokiller** [comment]
In general yes, but I probably won't have much free time in the next few months. I'll be happy to take a look when I do, though.

**Comment by simeg** [comment]
Hey @rcaloras. I'm looking into this but I'm having some problems setting up the environment to make the tests pass. I've installed `bats` and I can execute all tests but one `bats` test fail and a lot of other tests (running `py.test`) are failing.

Would you mind making a list of requirements or just some instructions on how to setup the project? Many thanks.

**Comment by rcaloras** [comment]
@simeg was thinking about this! I'll write a short doc on dev setup and contributions. Give me a couple days. Thanks!

**Comment by simeg** [comment]
@rcaloras Any update on this? The minimal amount of setup at least would be nice, that way me and maybe others could get started on contributing! Thanks.

**Comment by rcaloras** [comment]
@simeg I pulled together a brief contributors file that has some dev environment setup. https://github.com/rcaloras/bashhub-client/blob/master/CONTRIBUTING.md#dev-environment-setup

Give it a look and let me know if it helps.

**Comment by rcaloras** [comment]
@simeg Thanks a ton for your contributions on this. :100: :star:

**Comment by rcaloras** [comment]
Closing, feel free to reopen if there's more work here.

**Comment by rcaloras** [comment]
Cut https://github.com/rcaloras/bashhub-client/releases/tag/1.1.5

`bashhub update` for the latest.
