### ISSUE TITLE
Convert project to be compatible with Python 3. 

### ISSUE THREAD

**Issue by rcaloras** [rcaloras/bashhub-client#56]
Need to run the project through 2to3 and make sure everything is still working properly. If alls good, we can update to allow python3 as default installation type. I believe the project should continue to support Python 2 for old systems as Python 3 is still not the default Python installation on many servers.

**Comment by rcaloras** [comment]
Started a migration on this. Would love folks to try it by running the latest dev version and share feedback:
```
bashhub setup 2.0.0-dev
```

**Comment by kootenpv** [comment]
Hi! Not sure if this is related, but "bh" stopped working and I cannot update it?

**Comment by rcaloras** [comment]
@kootenpv thanks for reporting. Looks like there's an expired certificate. Investigating now.

**Comment by rcaloras** [comment]
@kootenpv Should be working again. let me know if you're still experiencing any issues.

**Comment by kootenpv** [comment]
Thanks for looking at it @rcaloras!

Unfortunately I'm still getting errors...

```
pascal@archbook:/home/pascal$ bh rsync
Sorry, looks like there's a connection error. Please try again later
pascal@archbook:/home/pascal$ bashhub update
Oops, looks like an exception occured: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

**Comment by rcaloras** [comment]
@kootenpv Try again. There was an obscure cert invalidation which is causing some older systems without updated certs to not work correctly. After some debugging and updating, I think this new cert chain should be backwards compatible for the next 8 years. 
  
https://www.ssl.com/blogs/addtrust-external-ca-root-expired-may-30-2020/

**Comment by rcaloras** [comment]
Now supporting Python 3.5-3.7 in https://github.com/rcaloras/bashhub-client/releases/tag/2.0.0
