### ISSUE TITLE
bh -dups -n 50000 is returning only 10k commands

### ISSUE THREAD

**Issue by ramakrishna-git** [rcaloras/bashhub-client#61]
Is there a way to download all of history? I have 30k commands in history by the command 
bh -dups -n 50000
is returning only 10k commands

**Comment by rcaloras** [comment]
Hey @ramakrishna-git, thanks for opening an issue for this. You're currently hitting the 10k cap that limits the number of commands returned. There's not currently a way to download your entire history through the cli/api. 

I think it'd make sense to put in an offset/skip param of some sort. That'd at least allow users to page through responses of commands. Would love your help with a PR if you have a ideas on how to implement it on the client side.

What's your username? I can support you directly if you want an export.

**Comment by rcaloras** [comment]
Resolving via DM.
