### ISSUE TITLE
Use Asciinema.org casts instead of GIFs

### ISSUE THREAD

**Issue by deeplook** [rcaloras/bashhub-client#63]
These can be paused, etc... But, yes, sadly on GitHub they won't render directly... See http://asciinema.org.

**Comment by waldyrious** [comment]
> Sadly on GitHub they won't render directly

I've opened https://github.com/isaacs/github/issues/1221 to help the community track this.

**Comment by rcaloras** [comment]
@deeplook thanks for the suggestion! The rendering and autoplay are two must haves for me with the current readme. They're much more engaging. If github adds support I'll be happy to add this.
