### ISSUE TITLE
Searching for "down" yields no results

### ISSUE THREAD

**Issue by kootenpv** [rcaloras/bashhub-client#64]
I have this one in history: 

    docker-compose -f docker-compose.yml down

When I do `bh down` it does not find anything (certainly should find a lot more).

When I do `bh compose` it does find that one among others.

Any idea what this could be?

**Comment by rcaloras** [comment]
@kootenpv thanks for the feedback! Believe this is the same case as https://github.com/rcaloras/bashhub-client/issues/50 where 'down' is a stop word. I've actually started the migration mentioned on there regarding the text index so hoping to have this resolved soon. This feedback definitely boosts its priority.

**Comment by rcaloras** [comment]
This is fixed. Just finished re-indexing. Long overdue. Give it a try and thanks for the feedback @kootenpv!

**Comment by kootenpv** [comment]
You're very welcome! Glad to hear it's fixed for the next person looking for "down" 😁
