### ISSUE TITLE
Errors on zsh shell load without bash completion mode

### ISSUE THREAD

**Issue by taylorthurlow** [rcaloras/bashhub-client#65]
I need to add this to my `zshrc` to prevent errors on every shell load:

~~~~bash
autoload bashcompinit
bashcompinit
~~~~

Otherwise I get this error:
~~~~bash
bashcompinit:141: parse error near `>&'
/home/username/.bashhub//deps/bashhub_completion_handler.sh:8: command not found: complete
~~~~

I suppose this could be intended but I couldn't find any info on the issue. Using `zsh 5.4.2` and the latest `oh-my-zsh`.

**Comment by rcaloras** [comment]
@taylorthurlow thanks for opening! You shouldn't have to do this as these commands are explicitly called during shell initialization in bashhub.zsh: https://github.com/rcaloras/bashhub-client/blob/master/bashhub/shell/bashhub.zsh#L32

I'm not able to recreate this on my zsh version (5.0.2). Can you add some basic logging locally to bashhub.zsh to see if those commands are getting executed for you during shell startup/init? My guess is startup is being interrupted or it's not preserving those calls. I'll upgrade my zsh version to see if I can recreate as well.

**Comment by taylorthurlow** [comment]
@rcaloras Thanks for the quick reply!

I added a little "LOADING" print right before the lines you've highlighted:

~~~~bash
echo "LOADING"
# Install our tab completion.
autoload compinit && compinit
autoload bashcompinit && bashcompinit
source $BH_DEPS_DIRECTORY/bashhub_completion_handler.sh
~~~~

And I commented out the lines I added from my `.zshrc`. Opening a new shell results in:

~~~~bash
LOADING
bashcompinit:141: parse error near `>&'
/home/taylor/.bashhub//deps/bashhub_completion_handler.sh:8: command not found: complete
$> 
~~~~

So it does look to me like they're being executed, and before I get the errors regarding autocomplete anyways.

**Comment by rcaloras** [comment]
Closing out. Feel free to reopen as needed.
