### ISSUE TITLE
Adding History to bashub manually [feature-request]

### ISSUE THREAD

**Issue by sagarkar10** [rcaloras/bashhub-client#67]
Hi,
Great work with the project. I am suggesting a simple add-on to whatever exists in here. I want to push the history of my bash_history/zsh_history which is already there before I started using bashhub. Is that possible in the current installation? If not how useful is that feature.

**Comment by sagarkar10** [comment]
@rcaloras Please help me with this!

**Comment by rcaloras** [comment]
@sagarkar10 thanks for checking out bashhub! This is a common feature request. Here's the details how you can do it: https://github.com/rcaloras/bashhub-client/issues/42

If you're interested in adding an import command, would love a PR for this feature :+1:
