### ISSUE TITLE
Broken "install" page on bashhub.com

### ISSUE THREAD

**Issue by curusarn** [rcaloras/bashhub-client#69]
Clicking "install" on `bashhub.com` leads to `https://bashhub.com/install` which gives me 410.
```
This bashhub.com page can’t be found 
It may have been moved or deleted.
HTTP ERROR 410
```

**Comment by rcaloras** [comment]
@curusarn thanks for reporting. I'm unable to recreate try visiting https://bashhub.com/install again. Let me know if it's still an issue.
