### ISSUE TITLE
Failed to login and got success message

### ISSUE THREAD

**Issue by Benuuu** [rcaloras/bashhub-client#7]
I failed to login on the setup and got the following message:

```
Sorry looks like getting your info failed.                    Exiting...
Should be good to go! Please close and restart your terminal session.
```

**Comment by rcaloras** [comment]
Hmm did you reset your password and then later login by rerunning install? 

Looks like you got an additional system, but it doesn't look like you have any new commands coming from it: https://bashhub.com/u/admin

Wonder if the auto generation didn't hook something correctly. 

I'll fix the messaging for sure :)

**Comment by Benuuu** [comment]
It looks like OS X doesn't read .bashrc by default

http://apple.stackexchange.com/a/13019

**Comment by rcaloras** [comment]
Did you generate the files yourself or did you let Bashhub do it? I just tried to account for that in the pull request:

```bash
bash_config_source='
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi
'
```
```bash
# Create two config files .bashrc and .bash_profile since
# OS X and Linux shells use them diffferently. Source .bashrc
# from .bash_profile and everything should work the same now.
generate_bash_config_file() {
    touch ~/.bashrc
    touch ~/.bash_profile
    echo "$bash_config_source" >> ~/.bash_profile
    echo "Created ~/.bash_profile and ~/.bashrc"
}
```

Line 149 https://github.com/rcaloras/bashhub-client/commit/b1e165a54f986f868c71a200862fbfb9826bed58

**Comment by Benuuu** [comment]
That's probably the issue.  It looks like I generated the file myself.

**Comment by rcaloras** [comment]
Addressed this initial issue in the PR I merged. Thanks for reporting @Benuuu! Please keep feedback coming :+1:
