### ISSUE TITLE
"Looks like this box is already registered as ''" on new machine

### ISSUE THREAD

**Issue by kiedtl** [rcaloras/bashhub-client#71]
Today, I was setting up a new machine and tried to install Bashhub. already had another box going on.

Login was OK, but instead of prompting me to name this machine it welcomed me back as my old machine name. I need this to have a different name. Is this a bug or am I just really stupid? Or both?

**Comment by rcaloras** [comment]
Hey @kiedtl thanks for opening!

Bashhub identifies system's via it's mac address. During setup this line should be able to finger print your system: https://github.com/rcaloras/bashhub-client/blob/16dc6cf45c9300dbd4263c6c2fbcda86a99db9d1/bashhub/bashhub_setup.py#L104

Are these systems VMs or something? One thing you could try is to run that command in a python terminal on both boxes and see which mac is produced. Maybe this method is not working on either box and it's just failing on both. Could you try this in a python terminal on each box and report back?:
```python
import uuid
uuid.getnode().__str__()
```

**Comment by kiedtl** [comment]
Now *that* explains it. I had installed Arch Linux on a USB drive, and before moving it to the computer I was planning to use it with I plugged it into my main computer and installed Bashhub. I'll try again on the other computer.

Thanks!

**Comment by kiedtl** [comment]
It worked!

**Comment by rcaloras** [comment]
Great! 👍 Let me know if you have any other feedback.
