### ISSUE TITLE
Removing Bashhub

### ISSUE THREAD

**Issue by oguevarah** [rcaloras/bashhub-client#72]
Hey! 
 The fact that you don't say that to eliminate this rare Bashhub thing, it must be deleted from the bash_completion.d directory of ubuntu, and not with a simple deletion of the directory, makes me think that it is developed with dark and malicious intentions

**Comment by rcaloras** [comment]
@oguevarah didn't realize you're required to remove from `bash_completion.d` as well.  Doing a default install via bash on my system does not manipulate that directory. Apologies if you think that's malicious in any way. I'm not able to recreate this.
