### ISSUE TITLE
This name is already registered for one of your systems

### ISSUE THREAD

**Issue by jpartain89** [rcaloras/bashhub-client#75]
So, following #71 's suggestion that @rcaloras posted, I went into my python prompt, and typed: 
```python
import uuid
uuid.getnode().__str__()
```
on two of my macOS-based machines (one macbook, and one iMac) and they are both returning the SAME UUID.... ARGH... 

What can I do from here to get this to work? Because I friggin love BashHub....

**Comment by rcaloras** [comment]
Hey @jpartain89 thanks for opening and the <3 for Bashhub! Apologies for not responding on this issue initially. Were you able to resolve this similar to #71 ?

**Comment by rcaloras** [comment]
Closing assuming this is resolved. @jpartain89 feel free to reopen if still an issue!
