### ISSUE TITLE
General Query: What privacy precautions and measures does bh take?

### ISSUE THREAD

**Issue by sudipbhandari126** [rcaloras/bashhub-client#76]
Want to know because sometimes we end up typing some secure info in terminal.. 'passwords , ssh keys' etc

**Comment by rcaloras** [comment]
Hey @sudipbhandari126, thanks for checking out Bashhub. You can find some details regarding this in the wiki's Security and Privacy section: https://github.com/rcaloras/bashhub-client/wiki/Security-and-Privacy

Feel free to reopen if you don't feel your question is answered there or in one of the other open issues.
