### ISSUE TITLE
zsh install requires default shell be zsh

### ISSUE THREAD

**Issue by rcaloras** [rcaloras/bashhub-client#8]
zsh install currently depends on it being configure as the default shell. During installation we detect the shell type and install the appropriate handlers. 

```bash
detect_shell_type() {
    if [ -n "$($SHELL -c 'echo $ZSH_VERSION')" ]; then
        echo 'zsh'
    elif [ -n "$($SHELL -c 'echo $BASH_VERSION')" ]; then
        echo 'bash'
    else
        :
    fi
}
```

Probably makes sense for Bashhub to hook zsh by default if `~/.zshrc` exists in addition to hooking your default bash profile. Also should update the readme and output to make this more obvious.

**Comment by rcaloras** [comment]
As a follow up, the `install-bashhub.sh` script fails under certain conditions if you execute it with zsh. Default is to execute it with bash, but would be nice to be compatible with zsh as well.

**Comment by rcaloras** [comment]
@akagi201
should now be able to hook and install for zsh by running setup via zsh. e.g.
```bash
curl -OL https://bashhub.com/setup && zsh setup
```
Thanks for the feedback! Please keep it coming :)

**Comment by Akagi201** [comment]
@rcaloras Thanks very much. I installed it on the zsh of my rmbp successfully.
