### ISSUE TITLE
uuid.getnode returns random numbers

### ISSUE THREAD

**Issue by casperdcl** [rcaloras/bashhub-client#82]
From the docs:

```
uuid.getnode = getnode()
    Get the hardware address as a 48-bit positive integer.
    
    The first time this runs, it may launch a separate program, which could
    be quite slow.  If all attempts to obtain the hardware address fail, we
    choose a random 48-bit number with its eighth bit set to 1 as recommended
    in RFC 4122.
```

So `bashhub` should check first for `uuid.getnode() & 0x10000000000`. If this is non-zero then it means `uuid.getnode()` will be a different randomly generated number each time it is run - not a unique system ID.

**Comment by rcaloras** [comment]
@casperdcl thanks for reporting. Did you run into a specific case where this occurred? Trying to understand how frequently this happens and if there's a better way to fingerprint systems.

**Comment by casperdcl** [comment]
I have this problem on one of my systems likely something which affects others too.

Looking into `uuid.getnode()` on python3, it'll try (in order)

```
_NODE_GETTERS_UNIX = [_unix_getnode, _ifconfig_getnode, _ip_getnode,   
                      _arp_getnode, _lanscan_getnode, _netstat_getnode]
```

where `_unix_getnode()` returns a different random number each time it's run on my system. `_ip_getnode()` is the only one which consistently returns the same number but it's not run since the earlier function(s) success and also it's not in python2.7 (I assume not a problem since #56 is fixed?)

Rather than hacking around with private `uuid` functions though it's probably best to change `bashhub` logic.

referring to https://github.com/rcaloras/bashhub-client/blob/ecfe678641c8bda3f0ea5df07c86c9b3cb045fa6/bashhub/bashhub_setup.py#L103-L104 maybe it's best to do:

```python
mac = uuid.getnode()
hostname = socket.gethostname()
if (uid >> 40) & 1:
    print("warning: identifying system based only on hostname ({})".format(hostname))
    mac = str(abs(hash(hostname)))  # or just mac = hostname
else:
    mac = mac.__str__()
```
