### ISSUE TITLE
Usability: accidental execution rather than inspection 

### ISSUE THREAD

**Issue by kootenpv** [rcaloras/bashhub-client#86]
Whenever I use 

    bh -i <something>

I always want to inspect it, not execute. 

I use `bh <something>` to print out a lot of commands, and then just select a printed line that I want by double clicking, paste and enter.

The problem is that when I use `bh -i <something>` I instinctively always hit Enter instead of space. That means I execute the new command, but the worst part about it is that this will change the metadata. So when I try to inspect again, it is overwritten.

Not sure if this is just me, but I just wanted to report this usability issue for me personally.

One idea would be to flip the space and enter keys, just to prevent losing data (even though it might be a surprise to some users). Maybe you have a better idea....

**Comment by rcaloras** [comment]
@kootenpv thanks for the feedback! I haven't heard this before and haven't experienced this myself. I guess as the original author 'space' felt like the natural command here :) 

> One idea would be to flip the space and enter keys, just to prevent losing data (even though it might be a surprise to some users). Maybe you have a better idea....

If interested, we could add a user custom key mapping in bashhub's config (i.e. ~/.bashhub/config) and then put values in: https://github.com/rcaloras/bashhub-client/blob/b11482c8c7c77e0fd59363a3a7b75cadf206cd5c/bashhub/i_search.py#L23-L32

Feel free to shoot a PR! 


> but the worst part about it is that this will change the metadata. So when I try to inspect again, it is overwritten.

Also, in case you accidentally run it, you can also run `bh -i -dups` to include duplicates to look at past invocations.

**Comment by kootenpv** [comment]
It was mostly about that I seemingly lost the information, so knowing that I can use `-dups` solves this issue for me :+1:

Other than that, I am fine with the current bindings :)

Thanks a lot for the quick reply!
