### ISSUE TITLE
Proxy bypass

### ISSUE THREAD

**Issue by usptact** [rcaloras/bashhub-client#89]
When on work VPN, I need to set proxy bypass to be able to use Bashhub. What is the address to use in my proxy bypass settings to make Bashhub work again?

**Comment by rcaloras** [comment]
Hey @usptact, not sure exactly your question or if it's possible to bypass your proxy/vpn. You would want to bypass for `https://bashhub.com` if possible though.

**Comment by usptact** [comment]
When connected to work VPN, I can't use bashhub search feature nor it appears new commands are stored for future searches.

**Comment by rcaloras** [comment]
@usptact This sounds like an issue with your VPN blocking access. If you can, set a bypass for `https://bashhub.com`. I'm not sure if this is possible with your vpn. Let me know if there's any more specific info I can provide to help.

**Comment by rcaloras** [comment]
Closing this as I dont believe this specific to bashhub. @usptact feel free to reopen if needed.
