### ISSUE TITLE
Can't install, probably because of homebrew-installed python?

### ISSUE THREAD

**Issue by formido** [rcaloras/bashhub-client#95]
I've installed python through homebrew earlier. When I try to install bashhub it fails. This is from the second attempt:

```shell
$ curl -OL https://bashhub.com/setup && bash setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8742  100  8742    0     0  17040      0 --:--:-- --:--:-- --:--:-- 17007

Looks like Bashhub is already installed.

Lets go ahead and update it.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    884      0 --:--:-- --:--:-- --:--:--   884
100   282  100   282    0     0    803      0 --:--:-- --:--:-- --:--:--   803
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 5001k  100 5001k    0     0  4465k      0  0:00:01  0:00:01 --:--:-- 8442k
Using base prefix '/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9'
New python executable in /Users/michael/.bashhub/env/bin/python3.9
Also creating executable in /Users/michael/.bashhub/env/bin/python
ERROR: The executable /Users/michael/.bashhub/env/bin/python3.9 is not functioning
ERROR: It thinks sys.prefix is '/usr/local/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9' (should be '/Users/michael/.bashhub/env')
ERROR: virtualenv is not compatible with this system or executable
```

Any chance bashhub could be made compatible with homebrew python installs?

**Comment by rcaloras** [comment]
@formido thanks for reporting! There's an improper version check I just fixed now in https://github.com/rcaloras/bashhub-client/commit/53ca7f25b955c5db08cbce196c300138c7893f75. Mind rerunning `curl -OL https://bashhub.com/setup && bash setup`. Feel free to post here if you're still experiencing any issues. 

Bashhub only supports up to Python 3.8, but shouldn't matter where it's installed. You may have have another version aside from 3.9, but it didn't look for it since this check failed.

**Comment by rcaloras** [comment]
@formido any update here?

**Comment by formido** [comment]
> @formido any update here

I'll check it out today

**Comment by formido** [comment]
@rcaloras It worked, thanks for being so quick! My friends and family are trying to warn me off with security scares but I'm going to trust you. YOLO!

**Comment by rcaloras** [comment]
FWIW, looks like your client isn't saving commands. https://bashhub.com/michaelterryio
May have to reinstall and check if preexec is working correctly.
