### ISSUE TITLE
Local Storage?

### ISSUE THREAD

**Issue by adjavaherian** [rcaloras/bashhub-client#98]
Is there a way to run this without the cloud support?

**Comment by rcaloras** [comment]
Hey @adjavaherian! No, Bashhub is designed specifically for the cloud and with multiple systems in mind. There are a few similar projects that might be of interest:
- https://github.com/nicksherron/bashhub-server (run your own backend instance of bashhub)
- https://github.com/curusarn/resh (local enhanced bash/zsh history)

Hope these help!
